baseURL = 'http://serabikocorbuyuni.my.id/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'serabi'

[[menu.nav]]
identifier = "Home"
name = "ihome"
url = "#"
weight = 1
[[menu.nav]]
identifier = "About"
url = "#"
name = "iabout"
url = "#about"
weight = 2
[[menu.nav]]
identifier = "Contact"
name = "tlp"
url = "#contact"
weight = 3
[[menu.nav]]
identifier = "Menu"
name = "imenu"
url = "#menu"
weight = 4
[[menu.nav]]
identifier = "Album"
name = "ialbum"
url = "#album"
weight = 5
# [[menu.follow]]
# identifier = "@serabikocorbuyuni"
# name = "fb"
# url = "https://facebook.com/serabikocorbuyuni"
# weight = 1
# [[menu.follow]]
# identifier = "@serabikocorbuyuni"
# name = "ig"
# url = "https://instagram.com/serabikocorbuyuni"
# weight = 2
# [[menu.follow]]
# identifier = "@serabikocorbuyuni"
# name = "tw"
# url = "https://twitter.com/serabibuyuni"
# weight = 3
