name: "Chromatic"

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*.ts'
      - '!src/**/*.d.ts'
      - 'src/**/*.css'
      - 'tailwind.config.mjs'
      - 'postcss.config.cjs'
      - 'astro.config.mjs'
  workflow_dispatch:
    inputs:
      my_input:
        description: 'testing e2e'
        required: true

jobs:
  install:
    name: Install Project
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
  build:
    name: Build Project
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: build blogger template
        run: pnpm build
      - name: build storybook
        run: pnpm build-storybook
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r storybook-static.zip storybook-static
  released:
    name: Released Project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/blogger.xml
            storybook-static.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}