name: "Build"

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*.ts'
      - '!src/**/*.d.ts'
      - 'src/**/*.css'
      - 'tailwind.config.mjs'
      - 'postcss.config.cjs'
      - 'astro.config.mjs'
  workflow_dispatch:
    inputs:
      title:
        description: 'testing e2e'
        required: false

jobs:
  install:
    name: Install Project
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: linter
        uses: ./.github/workflows/lint.yml
      - name: build blogger template
        run: pnpm build
      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/blogger.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}