name: "Chromatic"

on:
  pull_request:
    paths:
      - 'src/view/**'
      - '.github/workflows/chromatic.yml'
  workflow_dispatch:
    inputs:
      my_input:
        description: 'testing e2e'
        required: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: linter
        uses: ./.github/workflows/lint.yml
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
          skip: ${{ github.event.pull_request.draft == true }}
      - uses: actions/upload-artifact@v4
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            chromatic-diagnostics.json
            **/build-storybook.log